### ISSUE TITLE
Missing icon for start menu and blurred app icons

### ISSUE THREAD

**Issue by MichaIng** [raspberrypi-ui/lxpanel-buster#3]
When installing plain `lxde` package on an RPi with archive.raspberrypi.org APT repo applied, the start menu icon is missing and, compared to the Raspbian/Debian impression all application icons are obviously resized and hence are slightly blurred:
![rpi](https://user-images.githubusercontent.com/28480705/92996493-530d1380-f50c-11ea-8d8c-652374c5355b.png)
One can even change the icon in the menu settings, but it stays an empty button of minimal width as can be seen above when hovering.

When installing `lxpanel` and `lxpanel-data` from Raspbian repository, the issue is solved:
![debian](https://user-images.githubusercontent.com/28480705/92996514-910a3780-f50c-11ea-8bdf-5c060aeedf9d.png)
As well compare the application buttons, they are larger and sharp, obviously original size while resized and hence significantly blurred with the rpt build.

Again, same as with the [pcmanfm issue](https://github.com/raspberrypi-ui/pcmanfm-buster/issues/2), yes there is an easy solution (if one knows about it) but again the first impression for everyone installing plain `lxde` is broken. Not everyone knows or recognises that this is a build aimed for the complete RPi desktop only (?) and it is not placed on a separate RPi UI repo/suite since Buster, so one cannot easily apply the RPi kernel/firmware without having the RPi desktop packages applied as well. And in this case it looks more like a bug, as well resizing the icons is never a good idea in terms of their visual quality. I hope this makes it important enough to at least have a first look into it and see if there is a relatively simple fix possible and I'll assist as much as I can.

**Comment by spl237** [comment]
I've spent six years customising and improving LXDE specifically for Pi. We don't support the installation of plain LXDE.
