### ISSUE TITLE
LXQT version

### ISSUE THREAD

**Issue by maverick74** [raspberrypi-ui/lxpanel-buster#5]
I think this would fit more on feature request:

It Would be great to start plans to move pixel to lxqt, which has a few advantages over lxde...

**Comment by spl237** [comment]
We have no plans to do this; moving the entire desktop to Qt does not offer sufficient advantage over GTK+ to make the large amount of work involved worthwhile.

**Comment by maverick74** [comment]
I understand what you mean, but I must confess would still like to see it.

Lxqt looks much more "pretty" and up-to-date... (yes, I know their a bunch of silly reasons... I don't want to enter technical details like wayland and kwin and a few of other things that you for sure know a LOT better than I do...)

Out of curiosity - if you have the time to reply - Why Was lxde chosen and not lxqt (since the last already existed when pixel first came out)?

**Comment by spl237** [comment]
> Out of curiosity - if you have the time to reply - Why Was lxde chosen and not lxqt (since the last already existed when pixel first came out)?

LXQt was only added to Debian stable in Stretch. The first customised Raspberry Pi Desktop was based on Debian Wheezy, which predates Stretch by 2 versions. So LXQt may have existed, but not in a fashion that Debian considered it usable...

**Comment by maverick74** [comment]
@spl237 Thank you for taking the time on clarifying that. I now understand your move :).
thanks
